### ISSUE TITLE
nx required?

### ISSUE THREAD

**Issue by marco24690** [dkhrunov/ngx-mfe#13]
Should I use Nx and monorepo in order to use these library?
I'am using Angular v13 with @angular-architects/module-federation 12.5.3, so following the readme I should use ngx-mfe 1.0.2

**Comment by dkhrunov** [comment]
Hi, Nx monorepo isn't required

**Comment by dkhrunov** [comment]
Try to update to last version, in past versions was a bug with production build, see this issue https://github.com/dkhrunov/ngx-mfe/issues/7

**Comment by marco24690** [comment]
Sorry, my mistake, I am using Angular v12 can I update to the last version of ngx-mfe?

**Comment by dkhrunov** [comment]
Update to angular v13, angular-architect/module-federation to v14 and this lib to v2.1.0

**Comment by marco24690** [comment]
Thank you!

Marco
________________________________

**Comment by dkhrunov** [comment]
Happy to help!

Denis
