### ISSUE TITLE
Question: Use your lib with Nx MFE functionality

### ISSUE THREAD

**Issue by ArgV04** [dkhrunov/ngx-mfe#20]
Hello,

we are using Nx with its mfe functionality which looks similar to the architects approach but the question is if I can use your lib with Nx based mfe config flow together?

Thx

**Comment by dkhrunov** [comment]
Hello, 

Yes, you can use it with the Nx repository.
I created this functionality before Nx adopted a plugin based approach (mfe loading is embedded in the html template).
You can see examples [here](https://github.com/dkhrunov/fullstack-angular-mfe) and [here](https://github.com/dkhrunov/ngx-mfe-test).

**Comment by ArgV04** [comment]
Thx for fast response.  In your linked examples I still see the dep: angular-architects/module-federation listed. Is there any reason for this?

Thx

**Comment by dkhrunov** [comment]
> Thx for fast response. In your linked examples I still see the dep: angular-architects/module-federation listed. Is there any reason for this?
> 
> Thx

This library is based on @angular-architects/module-federation, it is highlighted in the documentation [here](https://github.com/dkhrunov/ngx-mfe/blob/31af65b0f2a3c2a99318183d4f94b49977506861/README.md?plain=1#L35).

**Comment by ArgV04** [comment]
Thats was my question :) is there a way to use Nx config MFE config way under the hood without angular-architects/module-federation but on top with your stuff? :)

**Comment by dkhrunov** [comment]
> Thats was my question :) is there a way to use Nx config MFE config way under the hood without angular-architects/module-federation but on top with your stuff? :)

Oh, my bad ^__^. I didn't understand you correctly.

I haven't tried this at the moment. I don't often work with MFE now, so I can't give you an honest answer.

**Comment by dkhrunov** [comment]
I will be grateful if you eventually find out this question yourself and write your result here.
