### ISSUE TITLE
Hi :-) any plans for angular 17/18?

### ISSUE THREAD

**Issue by out-dev** [dkhrunov/ngx-mfe#23]
Hi any plans to update this awesome library to use/excapt angular v17/18?

**Comment by out-dev** [comment]
Thank you sincerely for your tireless work on this repo. Your contributions are invaluable to the open source community. Could you kindly confirm if the repository is still actively maintained?

**Comment by dkhrunov** [comment]
Hello @out-dev 

ngx-mfe v17 released
MR #25

**Comment by dkhrunov** [comment]
Angular version 18 has not been released yet, target date is 2024-05-20
You can check it here https://angular.io/guide/releases#release-schedule
