### ISSUE TITLE
This is not recognized on outputs

### ISSUE THREAD

**Issue by hmendezm** [dkhrunov/ngx-mfe#6]
I followed the steps in your example everything works except when I try to use this. This always is undefined.

**HTML**
```
  <ng-container *mfeOutlet="'targetarea/Settings';outputs: { okEvent: next};">
      </ng-container>
```

**CODE BEHIND**
```
  public next(e) {

    if (e.sucess) {
      that.nameStep = true;
    }
  }
```

**Targetarea/Settings CODE**

```
export class SettingsComponent implements OnInit, AfterViewInit {
  @Output() public okEvent = new EventEmitter();
....


  public continue() {
    const projectTypes = PROJECTTYPES;
    this.okEvent.emit({ sucess: true });
  }

}

```

**Comment by hmendezm** [comment]
Hi dkrunov,

I updated *mfeOutlet as following

 <ng-container *mfeOutlet="'targetarea/Settings';outputs: { okEvent: next.**bind(this)**};">
      </ng-container>

**Comment by dkhrunov** [comment]
> 
> 
> 
> 
> Hi dkrunov,
> 
> 
> 
> I updated *mfeOutlet as following
> 
> 
> 
>  <ng-container *mfeOutlet="'targetarea/Settings';outputs: { okEvent: next.**bind(this)**};">
> 
>       </ng-container>

Hi, nice, I add this thing into the documentation, thanks!
